Revert "Add version command line option"
This reverts commit 2bc4acf27f841ee4e9554320ad03fa5d53f4b34b.

Fails with:
argparse.ArgumentError: argument --version/-v: conflicting option string(s): --version

Change-Id: I93fa8b29f53f10e75c73833072d0d79700d31f22
Signed-off-by: Kevin Hilman <khilman@baylibre.com>